PKG := "epid756"
VERSION := `Rscript -e "cat(read.dcf('DESCRIPTION')[,'Version'])"`
TARBALL := PKG + "_" + VERSION + ".tar.gz"

default: clean docs lint test check-cran

[unix]
[doc('Clean up auxiliary files and directories')]
clean:
	rm -f *.tar.gz
	rm -rf *.Rcheck/
	rm -rf .Rproj.user/

[doc('Ensure local NAMESPACE exists (bootstrapped if missing, as it is gitignored)')]
bootstrap-namespace:
	@if [ ! -f NAMESPACE ]; then \
		echo "# Generated by roxygen2: do not edit by hand" > NAMESPACE; \
	fi

[doc('Regenerate roxygen output: man/*.Rd and NAMESPACE')]
docs: bootstrap-namespace
	#!/usr/bin/env Rscript
	if (require(roxygen2)) roxygen2::roxygenize() else stop("missing 'roxygen2'")

[doc('Check R code using lintr')]
lint: bootstrap-namespace
	#!/usr/bin/env Rscript
	if (require(devtools)) devtools::load_all() else stop("missing 'devtools'")
	if (require(lintr)) lintr::lint_package() else stop("missing 'lintr'")

[doc('Run unit tests using devtools')]
test: bootstrap-namespace
	#!/usr/bin/env Rscript
	library(devtools)
	devtools::test()

[doc('Build package tarball')]
build: docs
	R CMD build .

[doc('Check built tarball with R CMD check')]
check: build
	R CMD check {{ TARBALL }} --no-manual

[doc('Check built tarball with CRAN settings')]
check-cran: build
	R CMD check {{ TARBALL }} --as-cran --no-manual

[doc('Install development version of package')]
install: docs
	R CMD INSTALL .

[doc('Remove package')]
remove:
	R CMD REMOVE {{ PKG }}
